### PR TITLE
Pick up new metadata for mioDAQ configurable digital voltage feature

### PR DESCRIPTION
**Pull request by SiuFong-NI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nidaqmx-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Pickup new DAQmx metadata, updated attributes.py and enums.py.

### Why should this Pull Request be merged?

To support configurable digital voltage feature for mioDAQ.

### What testing has been done?

Ran `poetry run pytest` against 2 NI MAX configuration files specified in CONTRIBUTING.md.
image

### CODE REVIEW

**Comment by SiuFong-NI** [comment]
My first PR from github, just curious how do we complete a PR here? Do we have an auto-complete option?

**Review by zhindes — CHANGES_REQUESTED** [review]
Let's filter out the Power stuff since its not fully cooked. See Brad/my comments on the metadata PR.

**Comment by SiuFong-NI** [comment]
> Let's filter out the Power stuff since its not fully cooked. See Brad/my comments on the metadata PR.

Updated in latest commit, verified that generated files excluded CalculatedPower related stuff.


> > My first PR from github, just curious how do we complete a PR here? Do we have an auto-complete option?
> 
> There is, but you might need permission. I see this at the bottom: image
> 
> What do you see?

image

Just saw the statement mentioned "Merging can be performed automatically once the requested changes are addressed.", so I guess it does but just pending the condition.

**Review by zhindes — APPROVED** [review]

**Review by zhindes — APPROVED** [review]

**Comment by SiuFong-NI** [comment]
My latest commit was to pull latest [nidaqmx.proto](https://github.com/ni/nidaqmx-python/pull/653/files#diff-4874399c70f52f0ee4fbe1371f30941ac4a19a76994b642544d6f85b495ea748) from my grpc-device PR: https://github.com/ni/grpc-device/pull/1115

**Review by bkeryan — APPROVED** [review]

**Comment by SiuFong-NI** [comment]
image

Looks like I do not have permission to complete the merge in this repo, @zhindes probably need you help on completing this PR.

**Comment by charitylxy** [comment]
@SiuFong-NI completed the PR for you

**Comment by SiuFong-NI** [comment]
Thanks @charitylxy for the help. Initially I was waiting for the https://github.com/ni/grpc-device-scrapigen/pull/251 to be merged first, I guess this change is independent so probably safe to merge first.

**Pull request merged**
